DROP DATABASE IF EXISTS pet_adoption;
CREATE DATABASE pet_adoption CHARACTER SET UTF8 COLLATE utf8_unicode_ci;
USE pet_adoption;

DROP TABLE IF EXISTS permission;
CREATE TABLE IF NOT EXISTS permission (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(15) NOT NULL,
    description VARCHAR(50)
);

DROP TABLE IF EXISTS role;
CREATE TABLE IF NOT EXISTS role (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(15) NOT NULL
);

DROP TABLE IF EXISTS role_permission;
CREATE TABLE IF NOT EXISTS role_permission (
    role_id INT UNSIGNED NOT NULL,
    permission_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (role_id) REFERENCES role (`id`) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permission (`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS photo;
CREATE TABLE IF NOT EXISTS photo (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    photo VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS address;
CREATE TABLE IF NOT EXISTS address (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    city VARCHAR(45) NOT NULL
);

DROP TABLE IF EXISTS contact;
CREATE TABLE IF NOT EXISTS contact (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(15) NOT NULL,
    info VARCHAR(50)
);

DROP TABLE IF EXISTS post;
CREATE TABLE IF NOT EXISTS post (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    photo_id INT UNSIGNED NOT NULL,
    address_id INT UNSIGNED NOT NULL,
    contact_id INT UNSIGNED NOT NULL,
    pet_name VARCHAR(30) NOT NULL,
    description TEXT NOT NULL,
    created DATE NOT NULL,
    status VARCHAR(10) NOT NULL,
    valid VARCHAR(10) NOT NULL,
    FOREIGN KEY (photo_id) REFERENCES photo (`id`) ON DELETE CASCADE,
    FOREIGN KEY (address_id) REFERENCES address (`id`) ON DELETE CASCADE,
    FOREIGN KEY (contact_id) REFERENCES contact (`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    post_id INT UNSIGNED NOT NULL,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(40) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES post (`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS user_role;
CREATE TABLE IF NOT EXISTS user_role (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    role_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (role_id) REFERENCES role (`id`) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES user (`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS filter;
CREATE TABLE IF NOT EXISTS filter (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS post_filter;
CREATE TABLE IF NOT EXISTS post_filter (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    post_id INT UNSIGNED NOT NULL,
    filter_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (post_id) REFERENCES post (`id`) ON DELETE CASCADE,
    FOREIGN KEY (filter_id) REFERENCES filter (`id`) ON DELETE CASCADE
);