DROP DATABASE IF EXISTS pet_adoption;
CREATE DATABASE pet_adoption CHARACTER SET UTF8 COLLATE utf8_unicode_ci;
USE pet_adoption;

DROP TABLE IF EXISTS permission;
CREATE TABLE IF NOT EXISTS permission (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(10) NOT NULL,
    description VARCHAR(255)
);

DROP TABLE IF EXISTS role;
CREATE TABLE IF NOT EXISTS role (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(10) NOT NULL
);

DROP TABLE IF EXISTS role_permission;
CREATE TABLE IF NOT EXISTS role_permission (
    role_id INT UNSIGNED NOT NULL,
    permission_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES role (`id`) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permission (`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(40) NOT NULL
);

DROP TABLE IF EXISTS user_role;
CREATE TABLE IF NOT EXISTS user_role (
    user_id INT UNSIGNED NOT NULL,
    role_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (user_id,role_id),
    FOREIGN KEY (role_id) REFERENCES role (`id`) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES user (`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS city;
CREATE TABLE IF NOT EXISTS city (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    city VARCHAR(40) NOT NULL
);

DROP TABLE IF EXISTS post;
CREATE TABLE IF NOT EXISTS post (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    city_id INT UNSIGNED NOT NULL,
    pet_name VARCHAR(30) NOT NULL,
    description TEXT NOT NULL,
    created DATE NOT NULL,
    status VARCHAR(10) NOT NULL,
    valid VARCHAR(10) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (`id`) ON DELETE CASCADE,
    FOREIGN KEY (city_id) REFERENCES city (`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS photo;
CREATE TABLE IF NOT EXISTS photo (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    post_id INT UNSIGNED NOT NULL,
    photo VARCHAR(255) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES post (`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS contact;
CREATE TABLE IF NOT EXISTS contact (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    post_id INT UNSIGNED NOT NULL,
    name VARCHAR(15) NOT NULL,
    info VARCHAR(255) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES post (`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS filter;
CREATE TABLE IF NOT EXISTS filter (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS post_filter;
CREATE TABLE IF NOT EXISTS post_filter (
    post_id INT UNSIGNED NOT NULL,
    filter_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (post_id, filter_id),
    FOREIGN KEY (post_id) REFERENCES post (`id`) ON DELETE CASCADE,
    FOREIGN KEY (filter_id) REFERENCES filter (`id`) ON DELETE CASCADE
);